import {daysUntilExam,progressSummary,accuracySummary} from './dashboard.js';
import {answered,correct,eligible,submit,shuffle,newAttempt,retake,fullForm,cumulative,sectionPractice,remainingSeconds} from './engine.js';
const root=document.querySelector('#app'), key='secplus-practice-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let bank,sections,state={version:1,studied:[],attempt:null,history:[]},view='home',index=0,storageWarning='',selectedSections=['content-01'],selectedForm='A';
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageWarning='Browser storage is unavailable or full. Keep this page open and export a backup.';}}
function button(label,action,cls=''){return `<button class="${cls}" data-action="${action}">${label}</button>`;}
function notice(){return storageWarning?`<p role="alert" class="notice">${esc(storageWarning)}</p>`:'';}
function score(a){return a.questions.filter(q=>correct(q,a.answers[q.id])).length;}
function render(){document.body.classList.toggle('taking-exam',view==='quiz');root.innerHTML=notice()+(view==='quiz'?'':dashboard())+(view==='quiz'?quiz():view==='results'?results():home());updateTimer();root.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>act(el.dataset.action));root.querySelectorAll('[data-section]').forEach(el=>el.onchange=()=>{state.studied=el.checked?[...new Set([...state.studied,el.dataset.section])]:state.studied.filter(s=>s!==el.dataset.section);save();render();});root.querySelectorAll('[name="answer"]').forEach(el=>el.onchange=()=>{const a=state.attempt,q=a.questions[index];if(a.submitted)return; a.answers[q.id]=[...root.querySelectorAll('[name="answer"]:checked')].map(x=>x.value);save();render();root.querySelector(`[name="answer"][value="${el.value}"]`)?.focus();});root.querySelectorAll('[data-pick]').forEach(el=>el.onchange=()=>{selectedSections=el.checked?[...new Set([...selectedSections,el.dataset.pick])]:selectedSections.filter(id=>id!==el.dataset.pick);render();root.querySelector('.picker').open=true;});root.querySelector('#form')?.addEventListener('change',e=>selectedForm=e.target.value);root.querySelector('#import')?.addEventListener('change',importFile);root.querySelector('#missed')?.addEventListener('change',e=>{root.querySelectorAll('.review.correct').forEach(x=>x.hidden=e.target.checked);});}
function countdownText(){const days=daysUntilExam();return days>0?`${days} days`:days===0?'Exam day!':'Exam date passed';}
function dashboard(){
  const progress=progressSummary(state.studied,sections),summary=accuracySummary(state.history,sections);
  const rows=items=>items.map(r=>`<div class="accuracy-row"><span>${esc(r.title)}</span><strong>${r.percent===null?'Not attempted':r.percent+'%'}</strong><small>${r.right} / ${r.total} correct</small><progress max="100" value="${r.percent??0}" aria-label="${esc(r.title)} accuracy: ${r.percent===null?'not attempted':r.percent+' percent'}"></progress></div>`).join('');
  return `<section class="dashboard" aria-label="Study dashboard"><div class="dashboard-cards">
    <article><span class="eyebrow">UNTIL TEST DAY</span><strong id="exam-countdown">${countdownText()}</strong><span>September 28, 2026 · local calendar date</span></article>
    <article><span class="eyebrow">MODULES LEFT</span><strong>${progress.remaining}<small> / ${sections.length}</small></strong><span>${progress.completed} completed · mark modules studied below</span><progress value="${progress.completed}" max="${sections.length}" aria-label="Modules completed"></progress></article>
    <article><span class="eyebrow">LIFETIME ACCURACY</span><strong>${summary.overall.percent===null?'—':summary.overall.percent+'%'}</strong><span>${summary.overall.total?`${summary.overall.right} / ${summary.overall.total} correct across submitted attempts`:'Submit your first exam to see your accuracy'}</span></article>
    </div><section class="accuracy-details"><h2>Rolling accuracy by domain</h2><p class="subtle">Domain percentages use the most recent 20 submitted questions in each domain (or all available if fewer), including retakes. Exams are ordered by submission time; within each exam, its question order determines the latest questions. Overall and module percentages include all submitted answers. Unfinished exams are excluded. This is practice accuracy, not a predicted CompTIA score. Questions linked to multiple modules count in each relevant module, but only once overall.</p><h2>Exam domains · latest 20 questions each</h2><div class="accuracy-grid">${rows(summary.byDomain)}</div><details><summary>Course modules · lifetime accuracy</summary><div class="accuracy-grid">${rows(summary.bySection)}</div></details></section></section>`;
}
function home() {
  const count=progressSummary(state.studied,sections).completed;
  const available=eligible(bank, selectedSections).length;
  return `<section class="hero"><p class="eyebrow">YOUR SECURITY+ STUDY COMPANION</p>
    <h1>Practice with purpose.<br><em>Know where you stand.</em></h1>
    <p>Answer first. Review the reasoning after. Every question leads back to your course material.</p></section>
    <div class="stats"><div><strong>${count}<small> / 26</small></strong><span>Sections studied</span></div>
    <div><strong>${bank.length}</strong><span>Source-backed questions</span></div>
    <div><strong>${state.history.length}</strong><span>Completed attempts</span></div></div>
    ${state.attempt&&!state.attempt.submitted?`<div class="notice">You have an unfinished exam. ${button('Resume exam','resume','primary')}</div>`:''}
    <section><div class="section-head"><h2>Choose your practice</h2><span class="tag">ALL 26 SECTIONS</span></div>
    <p class="subtle">Expanded practice includes scenarios, calculations, evidence interpretation, and multiple-selection questions. Section exams include foundational review; cumulative selection prioritizes applied questions, and full forms use the applied bank. Topic coverage is still growing; hands-on PBQs are not included.</p>
    <div class="modes"><article><span class="number">01 / FOCUSED</span><h3>Section practice</h3>
    <p>Choose the area or areas you just studied. Each attempt uses every question currently available for your selection, up to 90.</p>
    <details class="picker"><summary>Choose sections (${selectedSections.length})</summary>
    ${sections.map(s=>`<label><input type="checkbox" data-pick="${s.id}" ${selectedSections.includes(s.id)?'checked':''}>${esc(s.title)}</label>`).join('')}</details>
    <small>${available} available · ${Math.min(90,available)} questions in this attempt</small>
    <button class="primary" data-action="start" ${!available?'disabled':''}>Start section exam →</button></article>
    <article><span class="number">02 / CONNECTED</span><h3>Cumulative practice</h3>
    <p>Practice all the areas marked studied. Each selection represents every studied section when there is room.</p>
    ${button('Start cumulative →','cumulative')}<small>${Math.min(40,eligible(bank,state.studied).length)} questions this attempt · ${eligible(bank,state.studied).length} available</small></article>
    <article><span class="number">03 / EXAM DAY</span><h3>Full practice exam</h3>
    <p>90 applied questions with a 90-minute target, coverage of all 28 primary objectives, and domain balance: 11 / 20 / 16 / 25 / 18.</p>
    <label for="form">Exam form</label><select id="form">${['A','B','C'].map(f=>`<option ${selectedForm===f?'selected':''}>${f}</option>`).join('')}</select>
    <button class="primary" data-action="full" ${count!==26?'disabled':''}>${count===26?'Start full exam →':`Study ${26-count} more sections to unlock`}</button>
    <small>Forms A–C have different sets with overlap. Retake a completed form to keep its exact questions.</small></article></div></section>
    <section class="lower"><div><h2>Your course progress</h2><p class="subtle">Mark each section after studying it. Preparation sections are excluded.</p>
    <div class="sections">${sections.map(s=>`<label><input type="checkbox" data-section="${s.id}" ${state.studied.includes(s.id)?'checked':''}><span><b>${String(s.content_order).padStart(2,'0')}</b> ${esc(s.title)}</span><small>${eligible(bank,[s.id]).length} questions</small></label>`).join('')}</div></div>
    <aside><h2>Recent attempts</h2>${state.history.length?state.history.slice().reverse().map((a,i)=>`<button class="history" data-action="history:${state.history.length-1-i}"><span>${new Date(a.submitted).toLocaleDateString()}<small>${esc(a.mode)}${a.retakeOf?' · Retake':''}</small></span><strong>${score(a)}/${a.questions.length} →</strong></button>`).join(''):'<p class="subtle">Your first result will appear here. Open any completed result to review and retake it.</p>'}
    <div class="backup"><h3>Keep your progress</h3><p>Export a backup to move browsers or protect against cleared browser data.</p>${button('Export progress','export')}<label class="file">Import backup<input id="import" type="file" accept="application/json"></label></div></aside></section>`;
}
function quiz(){const a=state.attempt,q=a.questions[index],done=a.questions.filter(q=>answered(q,a.answers[q.id])).length;return `<div class="section-head">${button('← Save & exit','home')}<span class="tag">${esc(a.mode)}${a.retakeOf?' · RETAKE':''}</span></div><section class="exam"><div class="section-head"><p class="eyebrow">QUESTION ${index+1} OF ${a.questions.length}</p><span>${done} answered</span></div><p id="timer" class="timer" role="timer"></p>${a.retakeOf?'<p class="subtle">Exact questions from your earlier exam, with a fresh order.</p>':''}<p class="subtle">${a.previouslySeen||0} of these questions appeared in completed attempts before this exam.</p><progress value="${done}" max="${a.questions.length}" aria-label="Questions answered"></progress><h1 class="question" tabindex="-1">${esc(q.stem)}</h1><p class="subtle">${q.type==='multiple'?`Select exactly ${q.correct.length} answers.`:'Select one answer.'} Feedback is shown after submission.</p><fieldset><legend class="sr">Answer choices</legend>${q.options.map((o,i)=>`<label class="option ${a.answers[q.id]?.includes(o.id)?'selected':''}"><input name="answer" type="${q.type==='multiple'?'checkbox':'radio'}" value="${o.id}" ${a.answers[q.id]?.includes(o.id)?'checked':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></label>`).join('')}</fieldset><div class="navigation"><button data-action="prev" ${index===0?'disabled':''}>← Previous</button>${button(index===a.questions.length-1?'Review answers':'Next question →',index===a.questions.length-1?'overview':'next','primary')}</div><nav class="question-grid" aria-label="Question navigation">${a.questions.map((q,i)=>`<button aria-label="Question ${i+1}${answered(q,a.answers[q.id])?', answered':', unanswered'}" ${i===index?'aria-current="step"':''} class="${answered(q,a.answers[q.id])?'done':''}" data-action="goto:${i}">${i+1}</button>`).join('')}</nav><p class="subtle">Review any question before submitting. Multi-select questions require all requested choices.</p><button class="primary" data-action="submit" ${done!==a.questions.length?'disabled':''}>Submit all answers</button><p id="message" role="status"></p></section>`;}
function results(){const a=state.attempt,n=score(a);return `${button('← Back to practice','home')}<section class="result-banner"><p class="eyebrow">EXAM COMPLETE</p><h1>${n}<small> / ${a.questions.length}</small></h1><h2>${Math.round(n/a.questions.length*100)}% correct · ${a.questions.length-n} to revisit</h2><p>Practice score, not a prediction of your CompTIA scaled score.</p>${button('Retake this exam ↻','retake','primary')}<p class="retake-note">Same questions and versions. New question and answer order. Your original result stays saved.</p></section><div class="section-head"><h2>Your answer review</h2><label><input id="missed" type="checkbox"> Only show missed questions</label></div>${a.questions.map((q,i)=>{let ok=correct(q,a.answers[q.id]);return `<article class="review ${ok?'correct':'incorrect'}"><span class="result-label">${ok?'CORRECT':'REVISIT'} · QUESTION ${i+1}</span><h3>${esc(q.stem)}</h3><p><b>Your answer:</b> ${q.options.filter(o=>a.answers[q.id]?.includes(o.id)).map(o=>esc(o.text)).join('; ')}</p><p><b>Correct answer:</b> ${q.options.filter(o=>q.correct.includes(o.id)).map(o=>esc(o.text)).join('; ')}</p><p>${esc(q.explanation)}</p>${q.distractor_rationales?.length?`<details><summary>Why the other choices do not fit</summary>${q.distractor_rationales.map(d=>`<p><b>${esc(q.options.find(o=>o.id===d.option_id)?.text||'Alternative')}:</b> ${esc(d.text)} <small>(Guide page ${d.page})</small></p>`).join('')}</details>`:''}<div class="citation">${esc(q.source.title)} · ${esc(q.source.section)} · PDF page ${q.source.page}<br>Objective ${esc(q.objective)} · Open your local course guide at this page.</div></article>`;}).join('')}`;}
function focusQuestion(){window.scrollTo({top:0,behavior:'instant'});root.querySelector('.question')?.focus({preventScroll:true});}
function launch(attempt) {
  const seen=new Set(state.history.flatMap(a=>a.questions.map(q=>q.id)));
  attempt.previouslySeen=attempt.questions.filter(q=>seen.has(q.id)).length;
  state.attempt=attempt;index=0;view='quiz';save();render();focusQuestion();
}
function start(mode) {
  if(state.attempt&&!state.attempt.submitted){index=state.attempt.currentIndex||0;view='quiz';render();focusQuestion();return;}
  try {
    let pool,extra={};
    if(mode==='Full practice') {
      if(sections.some(s=>!state.studied.includes(s.id)))throw Error('Complete all 26 content sections first.');
      pool=fullForm(bank,selectedForm);extra={form:selectedForm,timeLimitMinutes:90,sectionIds:sections.map(s=>s.id)};mode+=' '+selectedForm;
    } else if(mode==='Cumulative practice') {pool=cumulative(bank,state.studied);extra.sectionIds=[...state.studied];}
    else {pool=sectionPractice(bank,selectedSections);extra.sectionIds=[...selectedSections];}
    if(!pool.length)throw Error('Choose a section, or mark at least one section studied for cumulative practice.');
    launch(newAttempt(pool,mode,extra));
  } catch(e){alert(e.message);}
}
function updateTimer(){
  const countdown=root.querySelector('#exam-countdown');if(countdown)countdown.textContent=countdownText();
  const el=root.querySelector('#timer');if(!el)return;
  const seconds=remainingSeconds(state.attempt);
  if(seconds===null){el.hidden=true;return;}
  const elapsed=seconds<0,abs=Math.abs(seconds);
  el.textContent=(elapsed?'Overtime +':'Time remaining ')+Math.floor(abs/60)+':'+String(abs%60).padStart(2,'0')+(elapsed?' · Finish all answers, then submit.':' · Timer continues while away.');
}
setInterval(updateTimer,1000);
function act(action){const [name,value]=action.split(':');if(name==='start')return start('Section practice');if(name==='cumulative')return start('Cumulative practice');if(name==='full')return start('Full practice');if(name==='retake'){if(!state.attempt?.submitted)return;launch(retake(state.attempt));return;}if(name==='home')view='home';if(name==='resume'){index=state.attempt.currentIndex||0;view='quiz';}if(name==='prev')index--;if(name==='next')index++;if(name==='goto')index=Number(value);if(name==='overview'){const first=state.attempt.questions.findIndex(q=>!answered(q,state.attempt.answers[q.id]));if(first>=0)index=first;else{root.querySelector('[data-action="submit"]').focus();return;}}if(name==='submit'){try{state.attempt=submit(state.attempt);state.history.push(structuredClone(state.attempt));save();view='results';}catch(e){alert(e.message);return;}}if(name==='history'){if(state.attempt&&!state.attempt.submitted){alert('Finish your current exam before opening an older result.');return;}state.attempt=structuredClone(state.history[Number(value)]);view='results';}if(name==='export'){let u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=u;link.download='security-plus-progress.json';link.click();setTimeout(()=>URL.revokeObjectURL(u),1000);return;}if(view==='quiz'&&state.attempt&&!state.attempt.submitted){state.attempt.currentIndex=index;save();}render();if(view==='quiz')focusQuestion();else window.scrollTo({top:0,behavior:'instant'});}
function valid(s){if(s?.version!==1||!Array.isArray(s.studied)||!s.studied.every(id=>sections.some(x=>x.id===id))||!Array.isArray(s.history)||s.history.length>1000)return false;const check=a=>a&&typeof a.mode==='string'&&(!a.currentIndex||Number.isInteger(a.currentIndex)&&a.currentIndex>=0&&a.currentIndex<a.questions?.length)&&(!a.timeLimitMinutes||a.timeLimitMinutes===90)&&Number.isFinite(a.started)&&(!a.submitted||Number.isFinite(a.submitted))&&Array.isArray(a.questions)&&a.questions.length>0&&a.questions.length<=90&&new Set(a.questions.map(q=>q.id)).size===a.questions.length&&a.answers&&typeof a.answers==='object'&&a.questions.every(q=>typeof q.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(q.id)&&!['__proto__','constructor','prototype'].includes(q.id)&&typeof q.stem==='string'&&typeof q.explanation==='string'&&['single','multiple'].includes(q.type)&&Array.isArray(q.options)&&q.options.length>=2&&q.options.every(o=>typeof o.id==='string'&&/^[a-zA-Z0-9_-]{1,60}$/.test(o.id)&&typeof o.text==='string')&&new Set(q.options.map(o=>o.id)).size===q.options.length&&Array.isArray(q.correct)&&q.correct.length>0&&new Set(q.correct).size===q.correct.length&&(q.type!=='single'||q.correct.length===1)&&q.correct.every(id=>q.options.some(o=>o.id===id))&&q.source&&typeof q.source.title==='string'&&typeof q.source.section==='string'&&Number.isInteger(q.source.page)&&q.source.page>0&&(!q.distractor_rationales||Array.isArray(q.distractor_rationales)&&q.distractor_rationales.every(d=>typeof d.text==='string'&&typeof d.option_id==='string'&&Number.isInteger(d.page)))&&(!a.answers[q.id]||Array.isArray(a.answers[q.id])&&a.answers[q.id].every(id=>q.options.some(o=>o.id===id)))&&(!a.submitted||answered(q,a.answers[q.id])));return (!s.attempt||check(s.attempt))&&s.history.every(a=>a.submitted&&check(a));}
async function importFile(e){try{let f=e.target.files[0];if(!f)return;if(f.size>5000000)throw Error('Backup is too large.');let s=JSON.parse(await f.text());if(!valid(s))throw Error('This is not a valid version 1 progress backup.');if(!confirm('Replace progress in this browser with this backup? Export first if you want to keep your current progress.'))return;state=s;index=0;save();render();}catch(err){alert(err.message);}}
try{[bank,sections]=await Promise.all(['questions.json','sections.json'].map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('Could not load practice data.');return r.json();}));try{const raw=localStorage.getItem(key);if(raw){const s=JSON.parse(raw);if(valid(s))state=s;else storageWarning='Saved progress could not be loaded. Import a valid backup to recover it.';}}catch{storageWarning='Browser storage could not be read. Use export to keep your progress.';}render();}catch(e){root.innerHTML=`<h1>Practice could not load</h1><p>${esc(e.message)} Open this app using its hosted link or a local web server, then refresh.</p>`;}
