export const portCards = [
[21,'FTP','File Transfer Protocol','TCP','Controls file transfers; data uses a separate connection.'],
[22,'SSH / SCP / SFTP','Secure Shell / Secure Copy Protocol / SSH File Transfer Protocol','TCP','Encrypted remote commands and secure file transfers.'],
[23,'Telnet','Telnet (protocol name)','TCP','Unencrypted remote terminal access.'],
[25,'SMTP','Simple Mail Transfer Protocol','TCP','Transfers email between mail servers.'],
[53,'DNS','Domain Name System','TCP / UDP','Resolves domain names to addresses and other records.'],
[69,'TFTP','Trivial File Transfer Protocol','UDP','Simple file transfers, often boot files and device configurations.'],
[80,'HTTP','Hypertext Transfer Protocol','TCP','Transfers web resources without transport encryption.'],
[88,'Kerberos','Kerberos (protocol name)','TCP / UDP','Ticket-based authentication. The guide lists UDP; TCP is also supported.'],
[110,'POP3','Post Office Protocol version 3','TCP','Retrieves messages from a mail server.'],
[119,'NNTP','Network News Transfer Protocol','TCP','Reads, posts, and distributes newsgroup articles.'],
[123,'NTP','Network Time Protocol','UDP','Synchronizes computer and network-device clocks with time servers. Accurate clocks support consistent event logs and time-sensitive authentication.','https://www.rfc-editor.org/info/rfc5905/'],
[135,'RPC','Remote Procedure Call','TCP / UDP','Maps endpoints so clients can locate remote services; later calls may use other ports.'],
[137,'NetBIOS name service','Network Basic Input/Output System','TCP / UDP','Registers and resolves legacy network names; commonly uses UDP.'],
[138,'NetBIOS datagram service','Network Basic Input/Output System','UDP','Sends connectionless datagrams for legacy network applications.'],
[139,'NetBIOS session service','Network Basic Input/Output System','TCP','Provides sessions for legacy file and printer sharing.'],
[143,'IMAP','Internet Message Access Protocol','TCP','Accesses and synchronizes mail stored on a server.'],
[161,'SNMP','Simple Network Management Protocol','UDP','Queries and manages network devices.'],
[162,'SNMP traps','Simple Network Management Protocol','UDP','Receives device event notifications (traps).'],
[389,'LDAP','Lightweight Directory Access Protocol','TCP','Queries and updates directory entries such as users and groups.'],
[443,'HTTPS','Hypertext Transfer Protocol Secure','TCP','Encrypted web communication using Transport Layer Security (TLS). Modern HTTP/3 also uses UDP 443; the guide lists TCP.'],
[445,'SMB','Server Message Block','TCP','Shares files, printers, and network resources.'],
[465,'SMTPS','Simple Mail Transfer Protocol over Transport Layer Security (TLS)','TCP','Submits email with encryption established immediately (implicit TLS).'],
[500,'IKE / ISAKMP','Internet Key Exchange / Internet Security Association and Key Management Protocol','UDP','Negotiates authentication, keys, and security associations for Internet Protocol Security (IPsec) connections. This is the setup exchange, not the encrypted application traffic.','https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-ikee/93288c7a-0e71-45b7-b282-a1cb3dfeb725'],
[514,'Syslog','Syslog (system logging)','UDP','Sends event logs to a collector without built-in transport encryption.'],
[515,'LPD / LPR','Line Printer Daemon / Line Printer Remote','TCP','Submits print jobs to a network print queue using the line printer protocol. Supported by Windows and other operating systems; not exclusive to Windows printing.','https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements'],
[587,'SMTP submission','Simple Mail Transfer Protocol','TCP','Submits outgoing mail. STARTTLS upgrades the connection to Transport Layer Security (TLS), unlike implicit TLS on 465.'],
[636,'LDAPS','Lightweight Directory Access Protocol over Transport Layer Security (TLS)','TCP','Encrypted directory access.'],
[993,'IMAPS','Internet Message Access Protocol over Transport Layer Security (TLS)','TCP','Encrypted mailbox access and synchronization.'],
[995,'POP3S','Post Office Protocol version 3 over Transport Layer Security (TLS)','TCP','Retrieves email over an encrypted connection.'],
[1433,'Microsoft SQL Server','SQL: Structured Query Language','TCP','Connects to the default database engine instance to query and manage relational data.'],
[1645,'RADIUS authentication (legacy)','Remote Authentication Dial In User Service','UDP','Legacy network-access authentication and authorization; the assigned port is 1812.'],
[1646,'RADIUS accounting (legacy)','Remote Authentication Dial In User Service','UDP','Legacy session and usage accounting; the assigned port is 1813.'],
[1812,'RADIUS authentication','Remote Authentication Dial In User Service','UDP','Centralizes network-access authentication and authorization.'],
[1813,'RADIUS accounting','Remote Authentication Dial In User Service','UDP','Records network-access sessions and usage.'],
[3389,'RDP','Remote Desktop Protocol','TCP / UDP','Remote graphical desktop access. The guide lists TCP; modern implementations also use UDP.'],
[6514,'Syslog over TLS','Syslog over Transport Layer Security','TCP','Sends logs to a collector through an encrypted connection.']
].map(([port,protocol,fullName,transport,purpose,sourceUrl])=>({port,protocol,fullName,transport,purpose,sourceUrl,page:sourceUrl?null:port<=143?207:208}));
export const transportNames={TCP:'Transmission Control Protocol',UDP:'User Datagram Protocol','TCP / UDP':'Transmission Control Protocol / User Datagram Protocol'};
export const portSources=[
['NTP: clock synchronization on UDP 123','https://www.rfc-editor.org/info/rfc5905/'],
['Port registry','https://www.iana.org/assignments/service-names-port-numbers'],
['Protocol names','https://www.rfc-editor.org/info/rfc2000/'],
['Transport and NetBIOS names','https://www.rfc-editor.org/rfc/rfc2151'],
['Secure file transfer','https://www.openssh.org/specs.html'],
['IKE transport: UDP 500','https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-ikee/93288c7a-0e71-45b7-b282-a1cb3dfeb725'],
['Windows services','https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements'],
['Email encryption','https://www.rfc-editor.org/info/rfc8314/'],
['RADIUS authentication','https://www.rfc-editor.org/info/rfc2865/'],
['RADIUS accounting','https://www.rfc-editor.org/info/rfc2866/'],
['SQL full name','https://learn.microsoft.com/en-us/sql/odbc/reference/structured-query-language-sql']
];
